# Site wide configuration

title: Nikhil Karnik
locale: en_US
description: My Corner Of The Web
logo: NPK-logo-3.png
search: true
#url: http://nkarnik.github.io
url: http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Nikhil Karnik
  avatar: bio-photo-2.jpg
  email: nikhil.pankaj.karnik@gmail.com
  disqus-shortname:
  twitter: #username
  facebook: #username
  github: nkarnik
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: nikhil-karnik/41/192/788
  instagram: #username
  flickr: #username
  tumblr: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot: 
  bing-verify:
